import { useMemo, useState } from "react";
import { X } from "lucide-react";
import { AppShell } from "./components/AppShell";
import { OverviewPage } from "./features/OverviewPage";
import { BenchmarksPage } from "./features/benchmarks/BenchmarksPage";
import { ImportWorkspace } from "./features/import/ImportWorkspace";
import { MethodsPage } from "./features/MethodsPage";
import { ReportsPage } from "./features/ReportsPage";
import { ResultsWorkspace } from "./features/results/ResultsWorkspace";
import { sampleMappings, sampleResult } from "./data/sampleResult";
import {
  buildMappings,
  buildSpecFromMappings,
} from "./lib/browserAnalysis";
import { adaptDesktopEngineResult, toDesktopEngineSpec } from "./lib/desktopEngine";
import type {
  AnalysisSpec,
  FieldRole,
  ImportedDataset,
  ResultBundle,
  ViewKey,
} from "./types";

type ExperimentScreen = "results" | "import";

const sampleSpec: AnalysisSpec = {
  design: "randomized_ab",
  unitColumn: "unit_id",
  treatmentColumn: "treatment",
  outcomeColumn: "checkout_completed",
  controlValue: "0",
  treatmentValue: "1",
  outcomeType: "binary",
  alpha: 0.05,
  businessThreshold: 1.5,
  expectedAllocation: [0.5, 0.5],
  randomizedAssignmentConfirmed: true,
  covariateColumn: "pre_purchase_score",
};

const sampleDataset: ImportedDataset = {
  name: "checkout_incentive_synthetic_v1.csv",
  rawText: "Built-in deterministic synthetic demonstration",
  rows: [],
  columns: sampleMappings.map((mapping) => mapping.source),
  hash: "47ab1a639eecfbb1630063298d6d3b447bac5123e87d6e9653bdc283bf9de244",
  mappings: sampleMappings,
};

const escapeHtml = (value: string | number) =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");

function buildHtmlReport(bundle: ResultBundle) {
  const unitLabel = bundle.plan.outcomeType === "binary" ? "pp" : "units";
  const confidencePercent = Number(((1 - bundle.plan.alpha) * 100).toFixed(1));
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(bundle.projectName)} · CausalPilot Evidence Report</title>
<style>body{font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#101a3d;max-width:900px;margin:48px auto;padding:0 28px}h1{font-size:34px}h2{margin-top:36px;border-bottom:1px solid #ccd3df;padding-bottom:8px}.metric{display:inline-block;margin:8px 36px 8px 0}.metric strong{display:block;color:#0b55d9;font-size:27px}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #d9deea;text-align:left;padding:10px}code{font-size:12px;word-break:break-all}.footer{margin-top:48px;padding-top:20px;border-top:1px solid #ccd3df;color:#58627a}</style></head><body>
<p>CausalPilot AI · Evidence-linked report</p><h1>${escapeHtml(bundle.question)}</h1><p><strong>Project:</strong> ${escapeHtml(bundle.projectName)}</p>
<div class="metric"><span>Estimated effect</span><strong>${bundle.estimate.value > 0 ? "+" : ""}${bundle.estimate.value.toFixed(2)} ${unitLabel}</strong></div>
<div class="metric"><span>${confidencePercent}% confidence interval</span><strong>${bundle.estimate.ciLow.toFixed(2)} to ${bundle.estimate.ciHigh.toFixed(2)} ${unitLabel}</strong></div>
<div class="metric"><span>Business threshold</span><strong>${bundle.plan.businessThreshold.toFixed(2)} ${unitLabel}</strong></div>
<h2>Diagnostics</h2><table><thead><tr><th>Check</th><th>Status</th><th>Detail</th></tr></thead><tbody>${bundle.diagnostics.map((item) => `<tr><td>${escapeHtml(item.title)}</td><td>${escapeHtml(item.summary)}</td><td>${escapeHtml(item.detail)}</td></tr>`).join("")}</tbody></table>
<h2>Provenance</h2><p><strong>Dataset:</strong> ${escapeHtml(bundle.dataset.name)}</p><p><strong>Dataset hash:</strong> <code>${escapeHtml(bundle.dataset.hash)}</code></p><p><strong>Plan hash:</strong> <code>${escapeHtml(bundle.plan.hash)}</code></p><p><strong>Engine:</strong> ${escapeHtml(bundle.engineVersion)}</p><p><strong>Run ID:</strong> ${escapeHtml(bundle.runId)}</p>
<h2>Limitations</h2><ul>${bundle.limitations.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>
<div class="footer">Product author and evidence owner: <strong>LAI ZEYU (来泽宇)</strong><br>Generated by CausalPilot AI. Statistical values originate from the structured ResultBundle, not free-form AI generation.</div></body></html>`;
}

function downloadFile(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

export default function App() {
  const [currentView, setCurrentView] = useState<ViewKey>("experiments");
  const [experimentScreen, setExperimentScreen] = useState<ExperimentScreen>("results");
  const [result, setResult] = useState<ResultBundle>(sampleResult);
  const [dataset, setDataset] = useState<ImportedDataset | null>(null);
  const [spec, setSpec] = useState<AnalysisSpec | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [aboutOpen, setAboutOpen] = useState(false);
  const [desktopFileToken, setDesktopFileToken] = useState<string | null>(null);

  const renderedView = useMemo(() => {
    if (currentView !== "experiments") return currentView;
    return experimentScreen;
  }, [currentView, experimentScreen]);

  const navigate = (view: ViewKey) => {
    setCurrentView(view);
    if (view === "experiments") setExperimentScreen("results");
  };

  const openImport = () => {
    setCurrentView("experiments");
    setExperimentScreen("import");
    setError(null);
  };

  const openSampleImport = () => {
    setDataset(sampleDataset);
    setSpec(sampleSpec);
    setCurrentView("experiments");
    setExperimentScreen("import");
    setError(null);
    setDesktopFileToken(null);
  };

  const openSampleResult = () => {
    setResult(sampleResult);
    setCurrentView("experiments");
    setExperimentScreen("results");
    setError(null);
  };

  const chooseFile = async () => {
    if (!window.causalPilot) {
      setError(
        "Arbitrary CSV analysis requires the CausalPilot desktop app and its deterministic local engine. The frozen synthetic example remains available here.",
      );
      return;
    }
    setError(null);
    try {
      const selection = await window.causalPilot.selectExperimentFile();
      if (selection.cancelled) return;
      const mappings = buildMappings(selection.columns, []);
      const initialSpec = buildSpecFromMappings(mappings, []);
      setDataset({
        name: selection.displayName,
        rawText: "",
        rows: [],
        columns: selection.columns,
        hash: "pending:calculated-by-local-engine",
        mappings,
      });
      setSpec({ ...initialSpec, controlValue: "0", treatmentValue: "1" });
      setDesktopFileToken(selection.token);
      setCurrentView("experiments");
      setExperimentScreen("import");
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "The desktop file picker could not open the CSV.");
    }
  };

  const updateMapping = (source: string, role: FieldRole) => {
    setDataset((current) => {
      if (!current) return current;
      const mappings = current.mappings.map((mapping) =>
        mapping.source === source ? { ...mapping, role } : mapping,
      );
      const next = { ...current, mappings };
      if (current.rows.length) setSpec(buildSpecFromMappings(mappings, current.rows));
      return next;
    });
  };

  const validateAndContinue = async () => {
    if (!dataset || !spec) return;
    setError(null);
    const missing = [
      [spec.unitColumn, "unit ID"],
      [spec.treatmentColumn, "treatment assignment"],
      [spec.outcomeColumn, "primary outcome"],
    ].filter(([value]) => !value);
    if (missing.length) {
      setError(`Map a ${missing.map(([, label]) => label).join(", ")} before continuing.`);
      return;
    }
    setIsAnalyzing(true);
    try {
      let next: ResultBundle;
      if (dataset.rawText.startsWith("Built-in deterministic synthetic demonstration")) {
        next = sampleResult;
      } else if (desktopFileToken && window.causalPilot) {
        const engineResult = await window.causalPilot.analyzeExperiment({
          experimentFileToken: desktopFileToken,
          analysisSpec: toDesktopEngineSpec(spec, dataset.name.replace(/\.[^.]+$/, "")),
          requestId: `desktop-${Date.now()}`,
        });
        next = adaptDesktopEngineResult(engineResult, dataset, spec);
      } else {
        throw new Error(
          "Arbitrary CSV analysis requires the CausalPilot desktop app and its deterministic local engine.",
        );
      }
      setResult(next);
      setExperimentScreen("results");
      setCurrentView("experiments");
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "The experiment could not be analyzed.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const exportEvidence = async () => {
    if (window.causalPilot) {
      try {
        await window.causalPilot.exportEvidence(result);
        return;
      } catch {
        // The deterministic browser export remains available if the desktop bridge is unavailable.
      }
    }
    const base = result.projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    downloadFile(`${base}-result-bundle.json`, JSON.stringify(result, null, 2), "application/json");
    window.setTimeout(() => {
      downloadFile(`${base}-evidence-report.html`, buildHtmlReport(result), "text/html");
    }, 120);
  };

  return (
    <>
      <AppShell currentView={currentView} onNavigate={navigate} onShowAbout={() => setAboutOpen(true)}>
        {renderedView === "overview" && <OverviewPage onOpenSample={openSampleResult} onImport={openImport} />}
        {renderedView === "results" && (
          <ResultsWorkspace result={result} onImport={openImport} onExport={() => void exportEvidence()} onBackToOverview={() => navigate("overview")} />
        )}
        {renderedView === "import" && (
          <ImportWorkspace
            dataset={dataset}
            spec={spec}
            error={error}
            isAnalyzing={isAnalyzing}
            onBack={() => setExperimentScreen("results")}
            onChooseFile={() => void chooseFile()}
            onUseSample={openSampleImport}
            onMappingChange={updateMapping}
            onSpecChange={(patch) => setSpec((current) => (current ? { ...current, ...patch } : current))}
            onContinue={() => void validateAndContinue()}
          />
        )}
        {renderedView === "benchmarks" && <BenchmarksPage />}
        {renderedView === "reports" && <ReportsPage result={result} onExport={() => void exportEvidence()} />}
        {renderedView === "methods" && <MethodsPage />}
      </AppShell>

      {aboutOpen && (
        <div className="modal-backdrop" role="presentation" onMouseDown={() => setAboutOpen(false)}>
          <section className="about-modal" role="dialog" aria-modal="true" aria-labelledby="about-heading" onMouseDown={(event) => event.stopPropagation()}>
            <button className="modal-close" type="button" aria-label="Close About" onClick={() => setAboutOpen(false)}><X aria-hidden="true" /></button>
            <div className="about-brand-mark" aria-hidden="true"><i /><i /><i /></div>
            <h1 id="about-heading">CausalPilot AI</h1>
            <p className="about-version">English desktop MVP · Version 0.1.0</p>
            <p>An offline-first evidence workbench for randomized Marketing experiments and ethical team-level HR interventions.</p>
            <dl><div><dt>Product author</dt><dd>LAI ZEYU（来泽宇）</dd></div><div><dt>Problem & method owner</dt><dd>LAI ZEYU（来泽宇）</dd></div><div><dt>AI assistance</dt><dd>Research, prototyping, implementation support, and QA assistance are disclosed; deterministic code owns all statistical calculations.</dd></div></dl>
            <p className="about-boundary">Raw rows stay local by default. CausalPilot does not rank candidates or make individual employment decisions.</p>
          </section>
        </div>
      )}
    </>
  );
}
